# Naunet config document

[general]
creation_time = "13/12/2021 15:09:11"
name = "naunet_cuda_fake"
description = "example"

[chemistry]
elements = ["H", "D"]
pseudo_elements = []
species = ["H", "D", "H2", "HD"]
extra_species = []
network = "fake.krome"
database = "krome"
heating = []
cooling = []
rate_modifier = []
ode_modifier = []

[chemistry.dust]
type = "none"

[chemistry.binding_energy]

[chemistry.photon_yield]

[chemistry.shielding]

[ODEsolver]
solver = "cvode"
device = "gpu"
method = "cusparse"

[summary]
num_of_species = 4
num_of_reactions = 2
list_of_species = ["D", "H", "H2", "HD"]
